#!/usr/bin/env python3
"""Refresh the checked-in ALSA PCM snapshot. Requires beautifulsoup4."""
import concurrent.futures
import datetime
import json
from pathlib import Path
from urllib.parse import urljoin, urldefrag
from urllib.request import urlopen
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://www.alsa-project.org/alsa-doc/alsa-lib/'

def fetch(name):
    with urlopen(BASE + name, timeout=60) as response:
        return response.read()

def soup(raw):
    return BeautifulSoup(raw, 'html.parser')

def main():
    manual = soup(fetch('pcm.html'))
    core = soup(fetch('group___p_c_m.html'))
    groups = {'group___p_c_m.html': 'PCM interface'}
    for a in core.select('.memberdecls')[0].select('a.el'):
        groups[a['href']] = a.get_text(' ', strip=True)
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        documents = dict(zip(groups, pool.map(fetch, groups)))
    records, routes = [], {}

    def add(record, filename, fragment):
        record['source'] = BASE + filename + ('#' + fragment if fragment else '')
        records.append(record)
        routes[record['source']] = '#/' + record['id']
        for node in soup(record['html']).select('[id]'):
            routes[BASE + filename + '#' + node['id']] = '#/' + record['id'] + '/' + node['id']

    current = dict(id='manual/pcm', title='Digital audio fundamentals', category='PCM manual', html='')
    for child in manual.select_one('.textblock').children:
        if getattr(child, 'name', '') == 'h1':
            add(current, 'pcm.html', current['id'].split('/')[-1] if current['id'] != 'manual/pcm' else '')
            current = dict(id='manual/' + child.a['id'], title=child.get_text(' ', strip=True), category='PCM manual', html='')
        else:
            current['html'] += str(child)
    add(current, 'pcm.html', current['id'].split('/')[-1])
    for filename, raw in documents.items():
        doc = soup(raw)
        for item in doc.select('.memitem'):
            heading = item.find_previous_sibling('h2', class_='memtitle')
            if not heading:
                continue
            anchor = heading.select_one('.permalink a')['href'][1:]
            heading.select_one('.permalink').decompose()
            title = heading.get_text(' ', strip=True).removesuffix('()')
            add(dict(id='api/' + title, title=title, category=groups[filename], html=str(item)), filename, anchor)

    for record in records:
        doc = soup(record['html'])
        for el in doc.select('script, style, iframe, object, embed, form'):
            el.decompose()
        for el in doc.find_all(True):
            for attr in list(el.attrs):
                if attr not in ('href', 'src', 'id', 'class', 'colspan', 'rowspan', 'title', 'alt'):
                    del el[attr]
        for a in doc.select('a[href]'):
            absolute = urljoin(urldefrag(record['source'])[0], a['href'])
            a['href'] = routes.get(absolute, absolute)
            if not a['href'].startswith(('#/', 'https://', 'http://', 'mailto:')):
                del a['href']
        for img in doc.select('img[src]'):
            absolute = urljoin(record['source'], img['src'])
            filename = absolute.rsplit('/', 1)[-1]
            if filename in ('wave1.gif', 'wave2.gif'):
                (ROOT / 'assets' / filename).write_bytes(fetch(filename))
                img['src'] = 'assets/' + filename
                img['alt'] = 'Continuous sine waveform' if filename == 'wave1.gif' else 'Digitized sine waveform'
            else:
                img['src'] = absolute
        record['html'] = str(doc)
        record['text'] = doc.get_text(' ', strip=True)
        first = doc.select_one('.memdoc p, p')
        record['summary'] = first.get_text(' ', strip=True) if first else record['title']
    data = dict(source=BASE + 'pcm.html', fetched=datetime.datetime.now(datetime.timezone.utc).date().isoformat(), records=records, example=(ROOT / 'examples/playback.c').read_text())
    (ROOT / 'data.js').write_text('/* Generated by scripts/import_docs.py; upstream ALSA documentation. */\nwindow.ALSA_DOCS = ' + json.dumps(data, ensure_ascii=False) + ';\n')
    print(f'Imported {len(records)} entries from {len(documents) + 1} pages.')

if __name__ == '__main__':
    main()
